version: '3'

services:
  web:
    restart: always
    build: .
    ports:
      - "8000:8000"
    environment:
      DISCOUNT_SERVICE_URL: 'discount-service:50051'
    command: gunicorn backend.wsgi:application -w 2 -b :8000
  discount-service:
    image: hashorg/hash-mock-discount-service
    expose:
      - "50051"